# Generated by Django 5.1.1 on 2024-09-19 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_pedido_nombre_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='producto',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
